package com.ciam.Entity;

import java.util.Date;

public class DrUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.ENABLED
     *
     * @mbg.generated
     */
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.ACCOUNT_EXPIRED
     *
     * @mbg.generated
     */
    private Integer accountExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.CREDENTIAL_EXPIRED
     *
     * @mbg.generated
     */
    private Integer credentialExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.ACCOUNT_LOCKED
     *
     * @mbg.generated
     */
    private Integer accountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.GENDER
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.EMERGENCY_PHONE
     *
     * @mbg.generated
     */
    private String emergencyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.ORG_ID
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DR_USER.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.USER_ID
     *
     * @return the value of DR_USER.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.USER_ID
     *
     * @param userId the value for DR_USER.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.USER_NAME
     *
     * @return the value of DR_USER.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.USER_NAME
     *
     * @param userName the value for DR_USER.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.PASSWORD
     *
     * @return the value of DR_USER.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.PASSWORD
     *
     * @param password the value for DR_USER.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.ENABLED
     *
     * @return the value of DR_USER.ENABLED
     *
     * @mbg.generated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.ENABLED
     *
     * @param enabled the value for DR_USER.ENABLED
     *
     * @mbg.generated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.ACCOUNT_EXPIRED
     *
     * @return the value of DR_USER.ACCOUNT_EXPIRED
     *
     * @mbg.generated
     */
    public Integer getAccountExpired() {
        return accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.ACCOUNT_EXPIRED
     *
     * @param accountExpired the value for DR_USER.ACCOUNT_EXPIRED
     *
     * @mbg.generated
     */
    public void setAccountExpired(Integer accountExpired) {
        this.accountExpired = accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.CREDENTIAL_EXPIRED
     *
     * @return the value of DR_USER.CREDENTIAL_EXPIRED
     *
     * @mbg.generated
     */
    public Integer getCredentialExpired() {
        return credentialExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.CREDENTIAL_EXPIRED
     *
     * @param credentialExpired the value for DR_USER.CREDENTIAL_EXPIRED
     *
     * @mbg.generated
     */
    public void setCredentialExpired(Integer credentialExpired) {
        this.credentialExpired = credentialExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.ACCOUNT_LOCKED
     *
     * @return the value of DR_USER.ACCOUNT_LOCKED
     *
     * @mbg.generated
     */
    public Integer getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.ACCOUNT_LOCKED
     *
     * @param accountLocked the value for DR_USER.ACCOUNT_LOCKED
     *
     * @mbg.generated
     */
    public void setAccountLocked(Integer accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.NAME
     *
     * @return the value of DR_USER.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.NAME
     *
     * @param name the value for DR_USER.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.GENDER
     *
     * @return the value of DR_USER.GENDER
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.GENDER
     *
     * @param gender the value for DR_USER.GENDER
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.PHONE
     *
     * @return the value of DR_USER.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.PHONE
     *
     * @param phone the value for DR_USER.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.EMERGENCY_PHONE
     *
     * @return the value of DR_USER.EMERGENCY_PHONE
     *
     * @mbg.generated
     */
    public String getEmergencyPhone() {
        return emergencyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.EMERGENCY_PHONE
     *
     * @param emergencyPhone the value for DR_USER.EMERGENCY_PHONE
     *
     * @mbg.generated
     */
    public void setEmergencyPhone(String emergencyPhone) {
        this.emergencyPhone = emergencyPhone == null ? null : emergencyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.BIRTHDAY
     *
     * @return the value of DR_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.BIRTHDAY
     *
     * @param birthday the value for DR_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.REMARK
     *
     * @return the value of DR_USER.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.REMARK
     *
     * @param remark the value for DR_USER.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.ORG_ID
     *
     * @return the value of DR_USER.ORG_ID
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.ORG_ID
     *
     * @param orgId the value for DR_USER.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DR_USER.EMAIL
     *
     * @return the value of DR_USER.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DR_USER.EMAIL
     *
     * @param email the value for DR_USER.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}