package com.ciam.Mapper;

import com.ciam.Entity.DrUser;

public interface DrUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    int insert(DrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    int insertSelective(DrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    DrUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrUser record);
}